<a href="https://colab.research.google.com/github/aakashmohole/Machine-Learning-Phase_1-/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Numpy Basic operations  

In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2,3,5])
a

array([1, 2, 3, 5])

In [ ]:
a[0]

1

In [ ]:
a[3]

5

In [ ]:
b = np.array([[1,2],[3,4],[5,6]])
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
b.ndim

2

In [ ]:
b.itemsize

8

In [ ]:
b.shape

(3, 2)

In [ ]:
b = np.array([[1,2],[3,4],[5,6]], dtype=np.float64)
b

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [ ]:
b = np.array([[1,2],[3,4],[5,6]], dtype=np.complex128)
b

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

In [ ]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [ ]:
np.arange(1000)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [ ]:
print("string ex")
print(np.char.add(['Hallo','i am '],[' aakash',' raj']))

string ex
['Hallo aakash' 'i am  raj']


In [ ]:
print(np.char.multiply('okk ',5))

okk okk okk okk okk 


In [ ]:
print(np.char.center('Hello', 20 , fillchar = '*'))

*******Hello********


In [ ]:
print(np.char.capitalize("hello i am aakash"))

Hello i am aakash


In [ ]:
print(np.char.join(['-','*'],['abc','ok']))

['a-b-c' 'o*k']


In [ ]:
print(np.char.split(" a asdf  sdf sdfsdfdsa "))

['a', 'asdf', 'sdf', 'sdfsdfdsa']


In [ ]:
print(np.char.strip(['admin','aakash','okk'],'a'))


['dmin' 'kash' 'okk']
