<a href="https://colab.research.google.com/github/aakashmohole/Machine-Learning-Phase_1-/blob/main/Pandas_L1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

#  Let's Start :   ✈

---



In [ ]:
pd.__version__

'1.5.3'

Series create, manupulate, Querry, Delete !

---



In [ ]:
arr = [5,6,7,8,9]
s = pd.Series(arr)
s

0    5
1    6
2    7
3    8
4    9
dtype: int64

In [ ]:
order = [1,2,3,4,5]
s1 = pd.Series(arr,index = order)
s1

1    5
2    6
3    7
4    8
5    9
dtype: int64

In [ ]:
import numpy as np

n = np.random.rand(5)
index = ['a','b','c','d','e']

s3 = pd.Series(n,index = index)
s3

a    0.695776
b    0.811836
c    0.126861
d    0.771380
e    0.938862
dtype: float64

In [ ]:
print(s)
s.index = ['A',"B","C","D","E"]
s

0    5
1    6
2    7
3    8
4    9
dtype: int64


A    5
B    6
C    7
D    8
E    9
dtype: int64

In [ ]:
#Slicing
s[:3]


A    5
B    6
C    7
dtype: int64

In [ ]:
x = s.append(s1)
print(x)
x.drop('A')


A    5
B    6
C    7
D    8
E    9
1    5
2    6
3    7
4    8
5    9
dtype: int64


<ipython-input-13-dccc3810113b>:1: FutureWarning: The series.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  x = s.append(s1)


B    6
C    7
D    8
E    9
1    5
2    6
3    7
4    8
5    9
dtype: int64

Serie Operations

---



In [ ]:
print(s)
add = s.add(3)
print(add)
sub = s.sub(2)
print(sub)
mul = s.mul(2)
print(mul)

A    5
B    6
C    7
D    8
E    9
dtype: int64
A     8
B     9
C    10
D    11
E    12
dtype: int64
A    3
B    4
C    5
D    6
E    7
dtype: int64
A    10
B    12
C    14
D    16
E    18
dtype: int64


In [ ]:
print("Median: ",s.median())
print("Max: ",s.max())
print("Min: ",s.min())

Median:  7.0
Max:  9
Min:  5


#Creating Dataframe : ⛹

---

In [ ]:
dates = pd.date_range('today',periods = 6)
print(dates)

num_arr = np.random.rand(6,4)#row and columns
print(num_arr)

# uset the table column as the coloumn name
columns = ['A','B','C', 'D']
df1 = pd.DataFrame(num_arr, index = dates, columns = columns)
df1

DatetimeIndex(['2024-01-11 11:46:09.911366', '2024-01-12 11:46:09.911366',
               '2024-01-13 11:46:09.911366', '2024-01-14 11:46:09.911366',
               '2024-01-15 11:46:09.911366', '2024-01-16 11:46:09.911366'],
              dtype='datetime64[ns]', freq='D')
[[0.10929609 0.52191759 0.6207291  0.27000059]
 [0.19474406 0.5453023  0.83016459 0.62159885]
 [0.87048696 0.81732048 0.56775681 0.50004502]
 [0.14390151 0.69412928 0.71336766 0.9002923 ]
 [0.76269625 0.95446406 0.98512361 0.33126887]
 [0.73306966 0.14567659 0.77039255 0.15189844]]


A         B         C         D
2024-01-11 11:46:09.911366  0.109296  0.521918  0.620729  0.270001
2024-01-12 11:46:09.911366  0.194744  0.545302  0.830165  0.621599
2024-01-13 11:46:09.911366  0.870487  0.817320  0.567757  0.500045
2024-01-14 11:46:09.911366  0.143902  0.694129  0.713368  0.900292
2024-01-15 11:46:09.911366  0.762696  0.954464  0.985124  0.331269
2024-01-16 11:46:09.911366  0.733070  0.145677  0.770393  0.151898

from matplotlib import pyplot as plt
df1['A'].plot(kind='hist', bins=20, title='A')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
df1['B'].plot(kind='hist', bins=20, title='B')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
df1['C'].plot(kind='hist', bins=20, title='C')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
df1['D'].plot(kind='hist', bins=20, title='D')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
df1.plot(kind='scatter', x='A', y='B', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
df1.plot(kind='scatter', x='B', y='C', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
df1.plot(kind='scatter', x='C', y='D', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
df1['A'].plot(kind='line', figsize=(8, 4), title='A')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
df1['B'].plot(kind='line', figsize=(8, 4), title='B')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
df1['C'].plot(kind='line', figsize=(8, 4), title='C')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
df1['D'].plot(kind='line', figsize=(8, 4), title='D')
plt.gca().spines[['top', 'right']].set_visible(False)

In [ ]:
animalList = {
    'Animal':['Cat','Dog','Tiger','Monkey','Bear','Rabit'],
    'Age' : [3,5,1,3,5,7],
    'Visits': [1,2,1,1,1,2],
    'Suitable':['Yes','No','Yes','Yes','No','No']
}

srNo = [1,2,3,4,5,6]

df2 = pd.DataFrame(animalList, index = srNo)
df2

Animal  Age  Visits Suitable
1     Cat    3       1      Yes
2     Dog    5       2       No
3   Tiger    1       1      Yes
4  Monkey    3       1      Yes
5    Bear    5       1       No
6   Rabit    7       2       No

In [ ]:
df2.dtypes

Animal      object
Age          int64
Visits       int64
Suitable    object
dtype: object

In [ ]:
df2.head()


Animal  Age  Visits Suitable
1     Cat    3       1      Yes
2     Dog    5       2       No
3   Tiger    1       1      Yes
4  Monkey    3       1      Yes
5    Bear    5       1       No

In [ ]:
df2.head(3)

Animal  Age  Visits Suitable
1    Cat    3       1      Yes
2    Dog    5       2       No
3  Tiger    1       1      Yes

In [ ]:
df2.tail()

Animal  Age  Visits Suitable
2     Dog    5       2       No
3   Tiger    1       1      Yes
4  Monkey    3       1      Yes
5    Bear    5       1       No
6   Rabit    7       2       No

In [ ]:
df2.tail(3)

Animal  Age  Visits Suitable
4  Monkey    3       1      Yes
5    Bear    5       1       No
6   Rabit    7       2       No

In [ ]:
print(df2.index)
df2.columns

Int64Index([1, 2, 3, 4, 5, 6], dtype='int64')


Index(['Animal', 'Age', 'Visits', 'Suitable'], dtype='object')

In [ ]:
df2.values

array([['Cat', 3, 1, 'Yes'],
       ['Dog', 5, 2, 'No'],
       ['Tiger', 1, 1, 'Yes'],
       ['Monkey', 3, 1, 'Yes'],
       ['Bear', 5, 1, 'No'],
       ['Rabit', 7, 2, 'No']], dtype=object)

See Statical Data of  DataFrames

---



In [ ]:
df2.describe()

Age    Visits
count  6.000000  6.000000
mean   4.000000  1.333333
std    2.097618  0.516398
min    1.000000  1.000000
25%    3.000000  1.000000
50%    4.000000  1.000000
75%    5.000000  1.750000
max    7.000000  2.000000

Transpose The data

---



In [ ]:
df2.T

1    2      3       4     5      6
Animal    Cat  Dog  Tiger  Monkey  Bear  Rabit
Age         3    5      1       3     5      7
Visits      1    2      1       1     1      2
Suitable  Yes   No    Yes     Yes    No     No

from matplotlib import pyplot as plt
import seaborn as sns
_df_0.groupby(1).size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_1.groupby(2).size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_2.groupby(3).size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_3.groupby(4).size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp[2].value_counts()
    for x_label, grp in _df_4.groupby(1)
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel(1)
_ = plt.ylabel(2)

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp[3].value_counts()
    for x_label, grp in _df_5.groupby(2)
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel(2)
_ = plt.ylabel(3)

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp[4].value_counts()
    for x_label, grp in _df_6.groupby(3)
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel(3)
_ = plt.ylabel(4)

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp[5].value_counts()
    for x_label, grp in _df_7.groupby(4)
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel(4)
_ = plt.ylabel(5)

In [ ]:
df2.sort_values(by='Age')

Animal  Age  Visits Suitable
3   Tiger    1       1      Yes
1     Cat    3       1      Yes
4  Monkey    3       1      Yes
2     Dog    5       2       No
5    Bear    5       1       No
6   Rabit    7       2       No

In [ ]:
df2[1:3]

Animal  Age  Visits Suitable
2    Dog    5       2       No
3  Tiger    1       1      Yes

In [ ]:
df3 = df2.copy()
df3

Animal  Age  Visits Suitable
1     Cat    3       1      Yes
2     Dog    5       2       No
3   Tiger    1       1      Yes
4  Monkey    3       1      Yes
5    Bear    5       1       No
6   Rabit    7       2       No

In [ ]:
df2.iloc[2:4]

Animal  Age  Visits Suitable
3   Tiger    1       1      Yes
4  Monkey    3       1      Yes

In [ ]:
df2.isnull()

Animal    Age  Visits  Suitable
1   False  False   False     False
2   False  False   False     False
3   False  False   False     False
4   False  False   False     False
5   False  False   False     False
6   False  False   False     False

In [ ]:
print(df2)

df2.loc[4,'Age'] = 9
df2

   Animal  Age  Visits Suitable
1     Cat    3       1      Yes
2     Dog    5       2       No
3   Tiger    1       1      Yes
4  Monkey    9       1      Yes
5    Bear    5       1       No
6   Rabit    7       2       No


Animal  Age  Visits Suitable
1     Cat    3       1      Yes
2     Dog    5       2       No
3   Tiger    1       1      Yes
4  Monkey    9       1      Yes
5    Bear    5       1       No
6   Rabit    7       2       No

In [ ]:
df2.mean()

<ipython-input-54-4a56ca50fe8e>:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df2.mean()


Age       5.000000
Visits    1.333333
dtype: float64

In [ ]:
df2['Visits'].sum()

8

# Oprations on DataFrame missing Values

---



In [ ]:
meanAge = df3['Age'].mean()
df3['Age'].fillna(meanAge)

1    3
2    5
3    1
4    3
5    5
6    7
Name: Age, dtype: int64

In [ ]:
animalList2 = {
    'Animal':['Cat','Dog','Tiger','Monkey','Bear','Rabit'],
    'Age' : [3,5,np.nan,3,5,7],
    'Visits': [1,np.nan,1,1,1,np.nan],
    'Suitable':['Yes','No',np.nan,'Yes','No','No']
}

srNo = [1,2,3,4,5,6]

df4 = pd.DataFrame(animalList2, index = srNo)
df4

Animal  Age  Visits Suitable
1     Cat  3.0     1.0      Yes
2     Dog  5.0     NaN       No
3   Tiger  NaN     1.0      NaN
4  Monkey  3.0     1.0      Yes
5    Bear  5.0     1.0       No
6   Rabit  7.0     NaN       No

In [ ]:
meanAge = df4['Age'].mean()
df4['Age'].fillna(meanAge)
df4

Animal  Age  Visits Suitable
1     Cat  3.0     1.0      Yes
2     Dog  5.0     NaN       No
3   Tiger  NaN     1.0      NaN
4  Monkey  3.0     1.0      Yes
5    Bear  5.0     1.0       No
6   Rabit  7.0     NaN       No

In [ ]:
df4.dropna(how = 'any')

Animal  Age  Visits Suitable
1     Cat  3.0     1.0      Yes
4  Monkey  3.0     1.0      Yes
5    Bear  5.0     1.0       No

# DataFrame File Oprations  ♥

---
