In [2]:
import pandas as pd 
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.datasets import load_digits

In [3]:
digits = load_digits()

In [5]:
digits.data

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

In [6]:
digits.target

array([0, 1, 2, ..., 8, 9, 8])

In [7]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest =  train_test_split(digits.data, digits.target, test_size=0.2)

In [9]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit(xtrain, ytrain)
lr.score(xtest, ytest)

C:\Users\Aakash\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9555555555555556

In [10]:
from sklearn.svm import SVC
svm = SVC(gamma='auto')
svm.fit(xtrain, ytrain)
svm.score(xtest, ytest)

0.4361111111111111

In [14]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=40)
rf.fit(xtrain, ytrain)


RandomForestClassifier(n_estimators=40)

In [16]:
rf.score(xtrain, ytrain)

1.0

## **K Fold Cross Validation**

In [18]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [19]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [20]:
def get_score(model, xtrain, xtest, ytrain, ytest):
    model.fit(xtrain,ytrain)
    return model.score(xtest, ytest)

In [23]:
get_score(LogisticRegression(solver='liblinear',multi_class='ovr'),xtrain, xtest, ytrain, ytest)

0.9555555555555556

In [28]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

scores_logistic = []
scores_svm = []
scores_rf = []

for train_index, test_index in folds.split(digits.data,digits.target):
    xtrain, xtest, ytrain, ytest = digits.data[train_index], digits.data[test_index], \
                                       digits.target[train_index], digits.target[test_index]
    scores_logistic.append(get_score(LogisticRegression(solver='liblinear',multi_class='ovr'), xtrain, xtest, ytrain, ytest))  
    scores_svm.append(get_score(SVC(gamma='auto'), xtrain, xtest, ytrain, ytest))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=30), xtrain, xtest, ytrain, ytest))

In [25]:
scores_logistic

[0.8948247078464107, 0.9532554257095158, 0.9098497495826378]

In [26]:
scores_svm

[0.3806343906510851, 0.41068447412353926, 0.5125208681135225]

In [29]:
scores_rf

[0.9115191986644408, 0.9265442404006677, 0.9298831385642737]

## **cross_val_score function**

In [31]:
from sklearn.model_selection import cross_val_score
cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'), digits.data, digits.target,cv=6)

array([0.92666667, 0.93      , 0.94333333, 0.96989967, 0.94983278,
       0.88963211])

In [32]:
cross_val_score(SVC(gamma='auto'), digits.data, digits.target,cv=5)

array([0.41111111, 0.45      , 0.454039  , 0.44846797, 0.47910864])

In [34]:
cross_val_score(RandomForestClassifier(n_estimators=40),digits.data, digits.target,cv=5)

array([0.92222222, 0.90833333, 0.95264624, 0.96657382, 0.92200557])

## **Parameter Tuning with cvs**

In [35]:
score1 = cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'), digits.data, digits.target,cv=6)
np.average(score1)

0.9348940914158305

In [ ]:
score2 = cross_val_score(SVC(gamma='auto'), digits.data, digits.target,cv=6)
np.average(score2)